version: '2'
services:
    springify-app:
        image: springify
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://springify-postgresql:5432/springify
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=springify-elasticsearch:9300
        ports:
            - 8080:8080
    springify-postgresql:
        extends:
            file: postgresql.yml
            service: springify-postgresql
    springify-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: springify-elasticsearch
